stages:
  - test

test_idempotency:
  stage: test
  image: python:3.12-slim
  services:
    - name: postgres:15-alpine
      alias: postgres
  variables:
    POSTGRES_DB: wow_db
    POSTGRES_USER: migrator_user
    POSTGRES_PASSWORD: admin123
    POSTGRES_HOST: postgres
    POSTGRES_PORT: 5432
  before_script:
    - apt update && apt install -y postgresql-client diffutils
  script:
    - python test_idempotency.py
