global:
  scrape_interval: 5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-exporter:9187"]  # postgres-exporter виден внутри сети Docker как "postgres-exporter"

#  - job_name: "grafana"
#    metrics_path: "/metrics"
#    static_configs:
#      - targets: ["grafana:3000"]